### ISSUE TITLE
previous and next button not show 

### ISSUE THREAD

**Issue by ghost** [solution-loisir/eleventy-deep-pagination#2] opened 2022-01-12 13:23 UTC
When the tags in the posts are not the same, the before and after page buttons are not displayed, but when all the tags in the posts are the same, there is no problem.

**Comment by solution-loisir** [comment] 2022-01-15 20:22
Interesting. So if I understand correctly, when posts are not containing exactly the same tags , the `Next` and `Previous` button are not showing? And that would be on the first layer of `pagination` so the first listing page. I must admit I didn't test extensively as this was meant to be a quick demo more for myself than anything else. Although, I'm willing to investigate. I'll get back to you.

**Comment by solution-loisir** [comment] 2022-01-17 17:34
Hi @iamsavadkoohi, just published a version of the demo with posts not containing exactly the same tags. In my implementation the `Previous` and `Next` link as well the `First` and `Last` link are 'disabled' by design when the current page is corresponding to the link `href`. Here's an example for the `First` link:
```twig
<li>{% if page.url != pagination.href.first %}<a href="{{ pagination.href.first }}">First</a>{% else %}First{% endif %}</li>
```
You can find the modified demo here: https://eleventy-deep-pagination.netlify.app/.

**Comment by solution-loisir** [comment] 2022-03-17 01:58
To follow-up on this. There were actually a bug that was causing the behavior described in this issue. I just fixed. So everything should be working fine now. Just tested it! I am closing since the issue is resolved. Thanks!

**Closed as completed by solution-loisir** 2022-03-17 01:58 UTC
